package com.threefat.vcts.data.preferences

import android.content.Context
import android.content.SharedPreferences
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey

/**
 * Wraps an [EncryptedSharedPreferences] file used to persist the long-lived
 * refresh token across process restarts.
 *
 * Security model:
 *  - The master key is generated by [MasterKey] and stored in the Android
 *    Keystore (hardware-backed on devices that support StrongBox / TEE).
 *  - Values are AES-256-GCM-encrypted before they touch disk.
 *  - The refresh token is the only persisted credential; the access token
 *    lives in memory only (see [com.threefat.vcts.data.session.SessionStore]).
 *  - On logout we [clear] the file outright; subsequent reads return null.
 */
class SecureStore(context: Context) {

    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val prefs: SharedPreferences = EncryptedSharedPreferences.create(
        context,
        FILE_NAME,
        masterKey,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
    )

    var refreshToken: String?
        get() = prefs.getString(KEY_REFRESH_TOKEN, null)
        set(value) {
            prefs.edit().apply {
                if (value == null) remove(KEY_REFRESH_TOKEN) else putString(KEY_REFRESH_TOKEN, value)
            }.apply()
        }

    fun clear() {
        prefs.edit().clear().apply()
    }

    companion object {
        private const val FILE_NAME = "vcts_secure_prefs"
        private const val KEY_REFRESH_TOKEN = "refresh_token"
    }
}
