#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID_DIR="$ROOT_DIR/android"
APK_PATH="$ANDROID_DIR/app/build/outputs/apk/debug/app-debug.apk"

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
Builds the VCTS Android debug APK.

Usage:
  bash scripts/build-debug-apk.sh

Output:
  android/app/build/outputs/apk/debug/app-debug.apk

The script uses android/gradlew when present. If the Gradle wrapper has not
been generated by Android Studio yet, it falls back to a system `gradle`
command. Open android/ in Android Studio once and accept the Gradle wrapper
download prompt if neither command is available.
EOF
  exit 0
fi

if [[ ! -d "$ANDROID_DIR" ]]; then
  echo "Android project not found at: $ANDROID_DIR" >&2
  exit 1
fi

# The Gradle wrapper needs a JDK. Reuse the one bundled with Android Studio
# (JBR) when JAVA_HOME is not already pointing at a valid install, so teammates
# don't have to put Java on PATH manually.
resolve_java_home() {
  if [[ -n "${JAVA_HOME:-}" && -x "$JAVA_HOME/bin/java" ]]; then
    echo "$JAVA_HOME"; return 0
  fi
  local candidates=()
  case "$(uname -s)" in
    Darwin)
      candidates+=("/Applications/Android Studio.app/Contents/jbr/Contents/Home")
      ;;
    Linux)
      candidates+=("$HOME/android-studio/jbr" "/opt/android-studio/jbr" "/usr/local/android-studio/jbr")
      ;;
    *) # Windows (git bash / MSYS / Cygwin)
      candidates+=("/c/Program Files/Android/Android Studio/jbr" "/c/Program Files/Android/Android Studio Preview/jbr")
      ;;
  esac
  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -x "$candidate/bin/java" ]]; then
      echo "$candidate"; return 0
    fi
  done
  return 1
}

if JAVA_HOME="$(resolve_java_home)"; then
  export JAVA_HOME
  echo "Using JDK at: $JAVA_HOME"
else
  cat >&2 <<'EOF'
Could not find a JDK.

Set JAVA_HOME to a JDK 17+ install, or install Android Studio (its bundled JDK
ships under the Android Studio install directory as "jbr").
EOF
  exit 1
fi

# Point Gradle at the Android SDK on a fresh clone by writing local.properties
# when neither it nor ANDROID_HOME/ANDROID_SDK_ROOT is available.
LOCAL_PROPS="$ANDROID_DIR/local.properties"
if [[ ! -f "$LOCAL_PROPS" && -z "${ANDROID_HOME:-}" && -z "${ANDROID_SDK_ROOT:-}" ]]; then
  case "$(uname -s)" in
    Darwin) SDK_DIR="$HOME/Library/Android/sdk" ;;
    Linux)  SDK_DIR="$HOME/Android/Sdk" ;;
    *)      SDK_DIR="${LOCALAPPDATA:-$HOME/AppData/Local}/Android/Sdk" ;;
  esac
  # Gradle accepts forward slashes for sdk.dir on every platform, and the
  # normalized path is also what bash needs to stat the directory on Windows.
  SDK_DIR="${SDK_DIR//\\//}"
  if [[ -d "$SDK_DIR" ]]; then
    printf 'sdk.dir=%s\n' "$SDK_DIR" > "$LOCAL_PROPS"
    echo "Wrote SDK location to: $LOCAL_PROPS"
  else
    echo "Warning: Android SDK not found at $SDK_DIR. Set ANDROID_HOME if the build fails to find the SDK." >&2
  fi
fi

cd "$ANDROID_DIR"

if [[ -x "./gradlew" ]]; then
  GRADLE_CMD=("./gradlew")
elif [[ -f "./gradlew" ]]; then
  GRADLE_CMD=("bash" "./gradlew")
elif command -v gradle >/dev/null 2>&1; then
  GRADLE_CMD=("gradle")
else
  cat >&2 <<'EOF'
Could not find Gradle.

Fix one of these ways:
1. Open the android/ folder in Android Studio and accept the Gradle wrapper
   download prompt, then rerun this script.
2. Install Gradle 8.11+ and make sure `gradle` is on PATH.

Android Studio UI alternative:
Build -> Build Bundle(s) / APK(s) -> Build APK(s)
EOF
  exit 1
fi

echo "Building debug APK..."
"${GRADLE_CMD[@]}" :app:assembleDebug

if [[ ! -f "$APK_PATH" ]]; then
  echo "Build finished, but APK was not found at: $APK_PATH" >&2
  exit 1
fi

echo
echo "Debug APK created:"
echo "$APK_PATH"
