param(
    [switch]$Help
)

$ErrorActionPreference = "Stop"

$RootDir = Resolve-Path (Join-Path $PSScriptRoot "..")
$AndroidDir = Join-Path $RootDir "android"
$ApkPath = Join-Path $AndroidDir "app/build/outputs/apk/debug/app-debug.apk"

if ($Help) {
    @"
Builds the VCTS Android debug APK.

Usage:
  powershell -ExecutionPolicy Bypass -File scripts/build-debug-apk.ps1

Output:
  android/app/build/outputs/apk/debug/app-debug.apk

The script uses android/gradlew.bat or android/gradlew when present. If the
Gradle wrapper has not been generated by Android Studio yet, it falls back to a
system gradle command. Open android/ in Android Studio once and accept the
Gradle wrapper download prompt if neither command is available.
"@
    exit 0
}

if (-not (Test-Path $AndroidDir)) {
    throw "Android project not found at: $AndroidDir"
}

# The Gradle wrapper needs a JDK. Rather than forcing every teammate to put
# Java on PATH, reuse the JDK bundled with Android Studio (JBR) when JAVA_HOME
# is not already set to a valid install.
function Resolve-JavaHome {
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin/java.exe"))) {
        return $env:JAVA_HOME
    }

    $candidates = @(
        (Join-Path $env:ProgramFiles "Android/Android Studio/jbr"),
        (Join-Path ${env:ProgramFiles(x86)} "Android/Android Studio/jbr"),
        (Join-Path $env:LOCALAPPDATA "Programs/Android Studio/jbr"),
        (Join-Path $env:ProgramFiles "Android/Android Studio Preview/jbr")
    )
    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path (Join-Path $candidate "bin/java.exe"))) {
            return (Resolve-Path $candidate).Path
        }
    }
    return $null
}

$JavaHome = Resolve-JavaHome
if ($JavaHome) {
    $env:JAVA_HOME = $JavaHome
    Write-Host "Using JDK at: $JavaHome"
} else {
    @"
Could not find a JDK.

Set JAVA_HOME to a JDK 17+ install, or install Android Studio (its bundled JDK
lives at "C:\Program Files\Android\Android Studio\jbr").
"@ | Write-Error
    exit 1
}

# Point Gradle at the Android SDK on a fresh clone by writing local.properties
# when neither it nor ANDROID_HOME/ANDROID_SDK_ROOT is available.
$LocalProps = Join-Path $AndroidDir "local.properties"
if (-not (Test-Path $LocalProps) -and -not $env:ANDROID_HOME -and -not $env:ANDROID_SDK_ROOT) {
    $SdkDir = Join-Path $env:LOCALAPPDATA "Android/Sdk"
    if (Test-Path $SdkDir) {
        $Escaped = $SdkDir -replace '\\', '\\'
        "sdk.dir=$Escaped" | Set-Content -Path $LocalProps -Encoding ASCII
        Write-Host "Wrote SDK location to: $LocalProps"
    } else {
        Write-Warning "Android SDK not found at $SdkDir. Set ANDROID_HOME if the build fails to find the SDK."
    }
}

Push-Location $AndroidDir
try {
    if (Test-Path ".\gradlew.bat") {
        $GradleCmd = ".\gradlew.bat"
        $GradleArgs = @(":app:assembleDebug")
    } elseif (Test-Path ".\gradlew") {
        $GradleCmd = "bash"
        $GradleArgs = @(".\gradlew", ":app:assembleDebug")
    } else {
        $GradleOnPath = Get-Command "gradle" -ErrorAction SilentlyContinue
        if ($GradleOnPath) {
            $GradleCmd = "gradle"
            $GradleArgs = @(":app:assembleDebug")
        } else {
            @"
Could not find Gradle.

Fix one of these ways:
1. Open the android/ folder in Android Studio and accept the Gradle wrapper
   download prompt, then rerun this script.
2. Install Gradle 8.11+ and make sure gradle is on PATH.

Android Studio UI alternative:
Build -> Build Bundle(s) / APK(s) -> Build APK(s)
"@ | Write-Error
            exit 1
        }
    }

    Write-Host "Building debug APK..."
    & $GradleCmd @GradleArgs
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }

    if (-not (Test-Path $ApkPath)) {
        throw "Build finished, but APK was not found at: $ApkPath"
    }

    Write-Host ""
    Write-Host "Debug APK created:"
    Write-Host $ApkPath
} finally {
    Pop-Location
}
